apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/KubeCon-Demo/kubecon-2026-resources.git'
    targetRevision: main
    path: demo-app-helm 
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: demo-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true